In [52]:
import numpy as np

In [53]:
a=np.ones([3,4])
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [54]:
b=np.zeros([15])
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
c=np.empty([5,5])
c

array([[6.23042070e-307, 3.56043053e-307, 1.60219306e-306,
        7.56571288e-307, 1.89146896e-307],
       [1.37961302e-306, 1.05699242e-307, 8.01097889e-307,
        1.78020169e-306, 7.56601165e-307],
       [1.02359984e-306, 1.33510679e-306, 2.22522597e-306,
        1.33511018e-306, 6.23057689e-307],
       [7.56602524e-307, 8.45559303e-307, 8.06612616e-308,
        6.89810244e-307, 1.22387550e-307],
       [2.22522596e-306, 8.34423917e-308, 1.11261162e-306,
        1.78021527e-306, 2.46155235e-312]])

In [56]:
ar=np.arange(1,100,2)
ar

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [57]:
ab=np.array([1,2,3,4,5,6,7,8,9])
ab

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
abc=ab.reshape(3,3)
abc

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
abd=abc.flatten()
abd

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a1=np.array([[2,4,6,8],[1,3,5,7]])

In [61]:
a2=np.array([[9,10,11,12],[18,19,20,21]])

In [62]:
con=np.concatenate([a1,a2],axis=0)
con

array([[ 2,  4,  6,  8],
       [ 1,  3,  5,  7],
       [ 9, 10, 11, 12],
       [18, 19, 20, 21]])

In [63]:
vst=np.vstack((a1,a2))
vst

array([[ 2,  4,  6,  8],
       [ 1,  3,  5,  7],
       [ 9, 10, 11, 12],
       [18, 19, 20, 21]])

In [64]:
hst=np.hstack((a1,a2))
hst

array([[ 2,  4,  6,  8,  9, 10, 11, 12],
       [ 1,  3,  5,  7, 18, 19, 20, 21]])

In [65]:
arr=np.random.rand(6,3)
arr

array([[0.81707131, 0.89345612, 0.52150285],
       [0.95978323, 0.47312308, 0.50333974],
       [0.51466257, 0.45197326, 0.08816163],
       [0.34385381, 0.79470577, 0.6832197 ],
       [0.01417697, 0.78074141, 0.96893667],
       [0.97801011, 0.82300032, 0.95937179]])

In [66]:
arr1=np.arange(6)
arr1

array([0, 1, 2, 3, 4, 5])

In [67]:
rep=arr1.repeat(4)
rep

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5,
       5, 5])

In [68]:
ar2=arr1.cumprod()
ar2

array([0, 0, 0, 0, 0, 0], dtype=int32)

In [69]:
ar3=arr1.cumsum()
ar3

array([ 0,  1,  3,  6, 10, 15], dtype=int32)

In [70]:
aa1=np.arange(20)
aa1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [71]:
aa1.sum()

190

In [72]:
a12=np.array([2,4,3,7,5,6,8])

In [73]:
np.sort(a12)

array([2, 3, 4, 5, 6, 7, 8])

In [74]:
np.min(a12)

2

In [75]:
np.max(a12)

8

In [76]:
abcd = np.array([[1, 7], [6, 9]])
abcd


array([[1, 7],
       [6, 9]])

In [77]:
abcd.transpose()

array([[1, 6],
       [7, 9]])

In [78]:
np.identity(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [79]:
a = np.arange(10)

In [80]:
np.where(a>3)

(array([4, 5, 6, 7, 8, 9], dtype=int64),)

In [81]:
a=np.array([0,1,1])

In [82]:
a.any()

True